export const FETCH_REGIONS_REQUEST = 'FETCH_REGIONS_REQUEST';
export const FETCH_REGIONS_SUCCESS = 'FETCH_REGIONS_SUCCESS';
export const FETCH_REGIONS_FAILURE = 'FETCH_REGIONS_FAILURE';
export const POST_REGION_REQUEST = 'POST_REGION_REQUEST';
export const POST_REGION_SUCCESS = 'POST_REGION_SUCCESS';
export const POST_REGION_FAILURE = 'POST_REGION_FAILURE';
